/**
 * Groq adapter.
 *
 * This is the only module in the codebase that imports/talks to the
 * Groq SDK. services/aiProvider.js picks this adapter based on
 * AI_PROVIDER=groq and calls generateReply(messages, config) — nothing
 * else in the app (routes, controllers, frontend) knows Groq exists.
 *
 * Mirrors services/providers/openaiProvider.js's interface and error-
 * mapping conventions exactly, so aiProvider.js can treat every adapter
 * the same way.
 */
const Groq = require('groq-sdk');
const { AiProviderError } = require('../aiErrors');

const REQUEST_TIMEOUT_MS = 20000;
// Groq's model catalog changes over time; callers should normally set
// AI_MODEL explicitly. This is only a fallback if it's left blank.
const DEFAULT_MODEL = 'llama-3.3-70b-versatile';
const MAX_OUTPUT_TOKENS = 500;

const SYSTEM_PROMPT =
  'You are Bio Copilot, the research assistant built into BioAI Lab. ' +
  'You help researchers and students with molecular biology, genetics and ' +
  'bioinformatics questions. Be accurate and concise, and say clearly when ' +
  'you are not certain rather than guessing.';

var cachedClient = null;
var cachedKey = null;

function getClient(apiKey) {
  // Re-create the client if the key changes (e.g. between test runs);
  // otherwise reuse it so we're not constructing a new client per request.
  if (!cachedClient || cachedKey !== apiKey) {
    cachedClient = new Groq({
      apiKey: apiKey,
      timeout: REQUEST_TIMEOUT_MS,
      maxRetries: 1,
    });
    cachedKey = apiKey;
  }
  return cachedClient;
}

/**
 * Converts the app's existing { role, content } message format into
 * Groq's expected shape (OpenAI-compatible). The app already uses
 * 'user' | 'assistant' | 'system' roles, so this is mostly a safe
 * pass-through plus a default system prompt if the caller didn't supply one.
 */
function toGroqMessages(messages) {
  var cleaned = (messages || [])
    .filter(function (m) {
      return m && typeof m.content === 'string' && m.content.trim().length > 0;
    })
    .map(function (m) {
      var role = ['user', 'assistant', 'system'].indexOf(m.role) !== -1 ? m.role : 'user';
      return { role: role, content: m.content.trim() };
    });

  if (cleaned.length === 0 || cleaned[0].role !== 'system') {
    cleaned.unshift({ role: 'system', content: SYSTEM_PROMPT });
  }
  return cleaned;
}

/**
 * @param {Array<{role: string, content: string}>} messages
 * @param {{aiApiKey: string, aiModel: string}} config
 * @returns {Promise<string>} the assistant reply text
 */
async function generateReply(messages, config) {
  var client = getClient(config.aiApiKey);
  var model = config.aiModel || DEFAULT_MODEL;

  var completion;
  try {
    completion = await client.chat.completions.create(
      {
        model: model,
        messages: toGroqMessages(messages),
        temperature: 0.4,
        max_tokens: MAX_OUTPUT_TOKENS,
      },
      { timeout: REQUEST_TIMEOUT_MS }
    );
  } catch (err) {
    throw mapGroqError(err);
  }

  var reply =
    completion &&
    completion.choices &&
    completion.choices[0] &&
    completion.choices[0].message &&
    completion.choices[0].message.content;

  if (!reply || !reply.trim()) {
    throw new AiProviderError('EMPTY_RESPONSE', 'Groq returned an empty response.', {
      status: 502,
      retryable: true,
    });
  }

  return reply.trim();
}

/**
 * Translates Groq SDK errors into our own AiProviderError so the
 * controller never has to know anything about Groq's error shapes,
 * and so raw provider error text never reaches the client.
 *
 * groq-sdk is generated by the same tooling family as the OpenAI SDK
 * (Stainless), so it exposes a comparable `status` on API errors. We
 * check `status` first since it's the most reliable signal, then fall
 * back to name/code heuristics for timeout and network failures, and
 * finally a generic error so nothing throws unhandled.
 */
function mapGroqError(err) {
  var status = err && err.status;

  if (status === 401 || status === 403) {
    return new AiProviderError('PROVIDER_AUTH_ERROR', 'Groq rejected the configured API key.', {
      status: 502,
    });
  }
  if (status === 429) {
    return new AiProviderError('RATE_LIMITED', 'Groq rate limit reached.', {
      status: 429,
      retryable: true,
    });
  }
  if (status === 400) {
    return new AiProviderError('PROVIDER_BAD_REQUEST', 'Groq rejected the request as invalid.', {
      status: 502,
    });
  }
  if (typeof status === 'number' && status >= 500) {
    return new AiProviderError('PROVIDER_UNAVAILABLE', 'Groq is temporarily unavailable.', {
      status: 502,
      retryable: true,
    });
  }
  if (
    err &&
    (err.name === 'APIConnectionTimeoutError' || err.code === 'ETIMEDOUT' || err.type === 'request-timeout')
  ) {
    return new AiProviderError('PROVIDER_TIMEOUT', 'The request to Groq timed out.', {
      status: 504,
      retryable: true,
    });
  }
  if (err && (err.name === 'APIConnectionError' || err.code === 'ECONNREFUSED' || err.code === 'ENOTFOUND')) {
    return new AiProviderError('PROVIDER_NETWORK_ERROR', 'Could not reach Groq.', {
      status: 502,
      retryable: true,
    });
  }

  return new AiProviderError('PROVIDER_ERROR', 'Groq request failed.', {
    status: 502,
    retryable: true,
  });
}

module.exports = { generateReply };
